# Generated by Django 2.2.1 on 2021-02-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('alley', models.CharField(max_length=225)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Personnel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
