# Generated by Django 2.2.1 on 2021-02-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Personnel'),
        ),
    ]
