# Generated by Django 2.2.1 on 2021-02-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210216_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
