# Generated by Django 2.2.1 on 2021-02-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210216_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelPhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
    ]
