# Generated by Django 2.2.1 on 2021-02-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210221_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='destination_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Personnel'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='pay_code',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
