# Generated by Django 2.2.1 on 2021-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210221_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfasts', 'breakfasts'), ('pizzas', 'pizzas'), ('burgers', 'burgers'), ('seafoods', 'seafoods'), ('starters', 'starters'), ('salads', 'salads'), ('kebabs', 'kebabs'), ('gippos', 'gippos'), ('traditionals', 'traditionals')], default='breakfasts', max_length=30),
        ),
    ]
