# Generated by Django 2.2.1 on 2021-02-23 11:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.food_image_upload_path_handler),
        ),
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.branch_image_upload_path_handler),
        ),
    ]
