# Generated by Django 2.2.1 on 2021-02-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210223_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineorder',
            name='is_delivered',
        ),
    ]
