# Generated by Django 2.2.1 on 2021-02-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_onlineorder_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', 'not_delivered'), ('is_delivering', 'is_delivering'), ('delivered', 'delivered')], default='not_delivered', max_length=15),
        ),
    ]
