# Generated by Django 2.2.1 on 2021-02-25 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_onlineorder_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Branch'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_service',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
