# Generated by Django 2.2.1 on 2021-02-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210225_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='personnel_as_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_as_customer', to='core.Personnel'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to='core.Personnel'),
        ),
    ]
