# Generated by Django 2.2.1 on 2021-02-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210226_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='personnel_as_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_as_customer', to='core.Personnel'),
        ),
    ]
