# Generated by Django 2.2.1 on 2021-03-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reservetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_code',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
