# Generated by Django 2.2.1 on 2021-03-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210301_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_code', models.CharField(blank=True, default='0', max_length=255)),
                ('count', models.IntegerField()),
                ('delivery_status', models.CharField(choices=[('not_delivered', 'not_delivered'), ('delivered', 'delivered')], default='not_delivered', max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Branch')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Food')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personnel')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Table')),
            ],
        ),
    ]
