# Generated by Django 2.2.1 on 2021-03-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_store_storebranch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('store_code', 'product')},
        ),
    ]
